server:
  port: 10000

spring:
  application:
    name: user-freeboard-file-jwt

# sql구문 실행하라
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pmh
    username: root
    password: 1234

# create-drop은 세션이 종료될 때 같이 종료된다.
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
# 스프링부트 시작 한 후에 data.sql에 있는 insert 구문 실행하라.
    defer-datasource-initialization: true

  servlet:
     multipart:
       max-file-size: 100MB
       max-request-size: 100MB
       file-size-threshold: 0
  jwt:
    secret: abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd

my:
  value : "welcome to my value"

