server:
  port: 20000

spring:
  application:
    name: todo-kakao
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pmh?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true

msa:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyz01234567890

oauth:
  kakao:
    client_id: 3729987ab56f48c56116ec21b049a78e
    client_secret: rvxajLH92o1Lz9Joj69mju2A0pD5lVgi

