apiVersion: apps/v1
kind: Deployment # pod 여러개
metadata:
  name: mariadb-deployment
spec: # 어떻게 만들지 대한 내용
  replicas: 1 # 몇개의 pod 만들지?
  selector:
    matchLabels:
      app: mariadb #쿠버네팃 안에서 변수명
  template: #
    metadata:
      labels:
        app: mariadb # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: mariadb
          image: mariadb #dockerhub에 있는 image명
          ports:
            - containerPort: 3306 #default one
          env: #환경설정
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
          volumeMounts:
            - name: mariadb-initdb-config
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-initdb-config
          configMap:
            name: mariadb-initdb-config
--- #환경을 2개 만들고 싶을때 사용
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb